### ISSUE TITLE
Unable to authenticate into my gmail account with app generated password

### ISSUE THREAD

**Issue by mariofsylvia** [paulchakravarti/gmail-sender#11]
Hi,

When I try to use your gmail library with my email address and a generated app password for my gmail account, I receive an error: Username and Password not accepted.  I followed your reference material for setting up a generated password with Gmail and passed this into the Gmail instance.  I'm using python version 2.7.

thanks.

**Comment by paulchakravarti** [comment]
Closing as I can't replicate this - tests with app password still work.
