### ISSUE TITLE
Not finding GMail

### ISSUE THREAD

**Issue by doomline** [paulchakravarti/gmail-sender#14]
Hi, I installed the gmail package via pip install gmail. 

The CLI for this works, however when I go to run the basic commands 
import gmail

gmail = GMail('A.User<mygmail@gmail.com>','<my password>')
msg = Message('Test Message',to='mygmail@gmail.com',text='Test')
gmail.send(msg)

I get an error message stating that 'GMail' is not found. I went to the command line using python3 and it pulled up
 >>>
when I do 
>>> import gmail
it recognizes gmail, I tested this by doing 
>>> xyz
and got an error message. 

However when I used the GMail(), Message() or Send() it gives me an error saying it is not defined. When I put the import gmail in my IDE (VSCode) it states that it's an unresolved import. 

I went back and hit pip3 install gmail just to be certain and it said the requirement is already fulfilled. 

Thanks!

**Comment by TheLime1** [comment]
try
`from gmail import*
`
