### ISSUE TITLE
is the api dead ?

### ISSUE THREAD

**Issue by TheLime1** [paulchakravarti/gmail-sender#16]
![56](https://user-images.githubusercontent.com/47940043/160898108-5e15050f-89f9-4a0b-8901-b00a99ed331b.jpg)

**Comment by paulc** [comment]
Looks like it might be the case. This was a good (and useful) idea at the time but to be honest Gmail is getting increasingly user hostile so I suspect that it is probably time to switch to a different provider if you need this sort of functionality (I don't use this any more).

**Comment by ddouglas87** [comment]
I was able to figure it out.  As of writing this in late 2024 it still works, but you have to jump through a bunch of hoops.

I did not end up using this gmail library I ended up using smtplib, which comes with Python.  Though if you want this should work for this library too, just use different code than I did.

Steps:

1. Create a new gmail email for yourself that will send emails.  You will need a phone number.

2. In the new account go to account settings ([account.google.com](https://account.google.com/)) and enable two step verification.  This is required, you can't skip this step.  It will require your phone number again.

3. Gmail had a way to create a 3rd party app password.  The app (your python program) uses this secondary password, not the primary account password.  When a 3rd party password is enabled gmail will allow you to use smtp.  What I did was I found the old link path to turn it on [https://myaccount.google.com/u/4/apppassword](https://myaccount.google.com/u/4/apppasswords) (not the `u/4` in the url is the number to your account) and then from there I was able to create.  It then gave me a password to use.

4. This is example code I used which successfully used gmail to send an email:

```
    fromMy = 'your_new_email_address@gmail.com'
    to = 'your_old_email_address_youre_sending_to@gmail.com'
    subj = 'TheSubject'
    date = '2/1/2010'
    message_text = 'Hello Or any thing you want to send'

    msg = "From: %s\nTo: %s\nSubject: %s\nDate: %s\n\n%s" % (
        fromMy, to, subj, date, message_text)

    username = str('your_new_email_address@gmail.com')
    password = str('3rd party app password here')

    server = smtplib.SMTP("smtp.gmail.com", 587)
    server.starttls()
    server.login(username, password)
    server.sendmail(fromMy, to, msg)
    server.quit()
    print('ok the email has sent ')
```
