### ISSUE TITLE
[UPDATED]'GMail' object has no attribute 'session'

### ISSUE THREAD

**Issue by YasserAntonio** [paulchakravarti/gmail-sender#6]
Hello

first thanks for porting this lib to python 3.

I have some trouble to use it on python 3 because with this script :

> from gmail import GMail,Message
> 
> gmail = GMail(bytes(u"'A.User <"+gmail_user+">'", 'utf-8'), bytes(u"'"+gmail_password+"'", 'utf-8'))
> msg = Message(bytes(u"'"+object+"'"), to=bytes(u"'xyz <"+toaddr+">'"), text=bytes(u"'"+message+"'"))
> gmail.send(msg)

it keeps returning me this result  :

> /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5 "/Users/Yasser/Dropbox/Projects File/Python Apps/1. Applications/Talaria/Talaria.py"
> Traceback (most recent call last):
>   File "/Users/Yasser/Dropbox/Projects File/Python Apps/1. Applications/Talaria/Talaria.py", line 8, in <module>
>     gmail = GMail(bytes(u"'A.User <"+gmail_user+">'", 'utf-8'), bytes(u"'"+gmail_user+"'", 'utf-8'))
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gmail/gmail.py", line 57, in __init__
>     self.username = parseaddr(username)[1]
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/email/utils.py", line 218, in parseaddr
>     addrs = _AddressList(addr).addresslist
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/email/_parseaddr.py", line 500, in __init__
>     self.addresslist = self.getaddrlist()
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/email/_parseaddr.py", line 253, in getaddrlist
>     ad = self.getaddress()
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/email/_parseaddr.py", line 263, in getaddress
>     self.gotonext()
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/email/_parseaddr.py", line 236, in gotonext
>     if self.field[self.pos] in self.LWS + '\n\r':
> TypeError: 'in <string>' requires string as left operand, not int
> Exception ignored in: <bound method GMail.__del__ of <gmail.gmail.GMail object at 0x1022230f0>>
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gmail/gmail.py", line 144, in __del__
>     self.close()
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gmail/gmail.py", line 136, in close
>     if self.session:
> AttributeError: 'GMail' object has no attribute 'session'

> Process finished with exit code 1

Thank you for your help^^

**Comment by paulchakravarti** [comment]
I'm not sure why you are trying to pass the arguments as bytes - just pass the username/password/message etc as strings (unicode).

```
from gmail import *
gmail = GMail('xxx <xxx@gmail.com>','passwd')
msg = Message('Test Message', to='xxx <xxx@gmail.com>', text='Hello') 
gmail.send(msg)
```

**Comment by YasserAntonio** [comment]
I have followed your instruction with this code :

`from gmail import *
gmail = GMail('xxx '+ gmail_user,gmail_password)
msg = Message('Test Message', to='xxx '+ toaddr, text='Hello')
gmail.send(msg)`

where variables are only string without using bytes()

and i get this result:

`/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5 "/Users/Yasser/Dropbox/Projects File/Python Apps/1. Applications/Talaria/Talaria.py"
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gmail/gmail.py", line 73, in connect
    self.session.login(self.username,self.password)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/smtplib.py", line 729, in login
    raise last_exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/smtplib.py", line 720, in login
    initial_response_ok=initial_response_ok)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/smtplib.py", line 641, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials l2sm16453531wji.7 - gsmtp')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yasser/Dropbox/Projects File/Python Apps/1. Applications/Talaria/Talaria.py", line 12, in <module>
    gmail.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gmail/gmail.py", line 91, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gmail/gmail.py", line 76, in connect
    if e.smtp_error.startswith("5.7.14"):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
Exception ignored in: <bound method GMail.__del__ of <gmail.gmail.GMail object at 0x102200fd0>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gmail/gmail.py", line 144, in __del__
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gmail/gmail.py", line 137, in close
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/smtplib.py", line 978, in quit
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/smtplib.py", line 419, in docmd
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/smtplib.py", line 366, in putcmd
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/smtplib.py", line 356, in send
smtplib.SMTPServerDisconnected: Server not connected`

**Comment by paulchakravarti** [comment]
You need to upgrade to v.0.6.2 to fix the second error.

The error message is fairly clear - if you follow the instructions at the link provided in the email this will provide details on how to setup application specific passwords

Please don't continue to post basic usage errors - I'm not here to debug your application.

**Comment by YasserAntonio** [comment]
I'm on the v.0.6.2  and i have followed the message error instruction by lowering the security on the gmail account. I will not bother you anymore , good luck with your library.
